- hosts: node1
  remote_user: root
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: install httpd
    yum: name=httpd state=present
  - name: start httpd
    service: name=httpd state=started enabled=true

# ansible-playbook -i hosts first.yml
# 访问：http://192.168.33.140/